version: "3.8"

services:
  # app:
  #   build: .  # Assumes there is a Dockerfile in the current directory
  #   environment:
  #     DB_URL: "postgres://cargoshuttleuser:cargoshuttlepass@db:5432/postgres"
  #   depends_on:
  #     - db

  db:
    image: postgres:latest
    container_name: pgsql
    environment:
      POSTGRES_USER: cargoshuttleuser
      POSTGRES_PASSWORD: cargoshuttlepass
      POSTGRES_DB: postgres
    ports:
      - "5432:5432" # Map the PostgreSQL port to the host (optional)
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
