version: "3.8"

services:
  soko:
    build: .
    container_name: soko
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
    networks:
      - rs-net

  db:
    image: postgres:latest
    container_name: pgsql
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - local-pg-data:/var/lib/postgresql/data
    networks:
      - rs-net

volumes:
  local-pg-data:

networks:
  rs-net:
    driver: bridge
