version: "3.8"

services:
  soko:
    build: .
    container_name: soko
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - RUST_BACKTRACE=full
    networks:
      - s-net
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: pgsql
    environment:
      POSTGRESS_USER: postgres
      POSTGRES_PASSWORD: dbpass
      POSTGRES_DB: soko-db
    ports:
      - "5432:5432"
    volumes:
      - local-pg-data:/var/lib/postgresql/data
    networks:
      - s-net

volumes:
  local-pg-data:

networks:
  s-net:
    driver: bridge
